services:
  - type: web
    name: sip-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python-3.10.13

  - type: static
    name: sip-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
