services:
  - type: web
    name: smart-invest-backend
    env: docker
    plan: free
    rootDir: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PG_HOST
        sync: false
      - key: PG_PORT
        sync: false
      - key: PG_DATABASE
        sync: false
      - key: PG_USER
        sync: false
      - key: PG_PASSWORD
        sync: false
